name: Build .NET Framework 4.8 project

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Framework 4.8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build project
      run: dotnet build --configuration Release